# Generated by Django 4.1.3 on 2022-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeApp', '0002_cu_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='iqube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_color', models.CharField(max_length=30)),
                ('vehicle_desc', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=30)),
                ('regDte', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
