# Generated by Django 4.1.3 on 2022-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeApp', '0003_iqube'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqube',
            name='stock',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iqube',
            name='vehicle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
