# Generated by Django 4.1.3 on 2022-11-28 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeApp', '0004_iqube_stock_iqube_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('regDte', models.DateField(auto_now_add=True)),
                ('id_proof', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeApp.iqube')),
            ],
        ),
    ]
