# Generated by Django 4.1.3 on 2022-11-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeApp', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
